import type { UMGOverlayRow } from "./umgOverlayTypes";

export const UNIVERSAL_LATTICE_ROWS: UMGOverlayRow[] = [
  {
    rowId: "controller",
    rowIndex: 0,
    rowLabel: "Sleeve Controller",
    rowPurpose: "Activates the sleeve and determines whether this sleeve should handle the request.",
    allowedBlockTypes: ["neoblock", "gate"],
    routeRoles: ["controller"],
    siblingSemantics: "single_select",
    activationPolicy: "controller_always_on_when_overlay_selected",
  },
  {
    rowId: "intent",
    rowIndex: 1,
    rowLabel: "Intent / Domain Classification",
    rowPurpose: "Classifies what kind of work the request is asking for.",
    allowedBlockTypes: ["neoblock", "molt", "gate"],
    preferredRoles: ["trigger", "directive", "subject"],
    routeRoles: ["selector"],
    siblingSemantics: "multi_select",
    activationPolicy: "activate_on_prompt_match",
  },
  {
    rowId: "context_intake",
    rowIndex: 2,
    rowLabel: "Context Intake",
    rowPurpose: "Reads prompt, uploaded files, packages, repo context, and constraints.",
    allowedBlockTypes: ["neoblock", "molt", "tool", "capability"],
    preferredRoles: ["instruction", "subject", "primary"],
    routeRoles: ["reader"],
    siblingSemantics: "parallel",
    activationPolicy: "activate_on_package_match",
  },
  {
    rowId: "specialization",
    rowIndex: 3,
    rowLabel: "Specialization / Mode Selection",
    rowPurpose: "Selects language, platform, channel, market, audience, or working mode.",
    allowedBlockTypes: ["neoblock", "molt", "gate"],
    preferredRoles: ["subject", "directive", "primary"],
    routeRoles: ["selector", "constraint"],
    siblingSemantics: "multi_select",
    activationPolicy: "activate_on_prompt_match",
  },
  {
    rowId: "planning_composition",
    rowIndex: 4,
    rowLabel: "Planning / Composition",
    rowPurpose: "Plans work, selects blocks, composes NeoBlocks, and drafts missing pieces.",
    allowedBlockTypes: ["neoblock", "molt"],
    preferredRoles: ["directive", "instruction", "blueprint"],
    routeRoles: ["planner"],
    siblingSemantics: "parallel",
    activationPolicy: "activate_on_prompt_match",
  },
  {
    rowId: "capability_binding",
    rowIndex: 5,
    rowLabel: "Capability / Tool Binding",
    rowPurpose: "Determines which external or native tools are needed and available.",
    allowedBlockTypes: ["neoblock", "tool", "capability", "gate", "molt"],
    preferredRoles: ["primary", "instruction", "metaTool"],
    routeRoles: ["constraint", "worker"],
    siblingSemantics: "multi_select",
    activationPolicy: "activate_on_capability_required",
  },
  {
    rowId: "validation",
    rowIndex: 6,
    rowLabel: "Validation / Gatekeeping",
    rowPurpose: "Checks safety, compile eligibility, correctness, permissions, and risk.",
    allowedBlockTypes: ["neoblock", "gate", "molt"],
    preferredRoles: ["gate", "instruction", "philosophy"],
    routeRoles: ["validator"],
    siblingSemantics: "parallel",
    activationPolicy: "activate_on_validation_required",
  },
  {
    rowId: "execution",
    rowIndex: 7,
    rowLabel: "Execution / Draft Action",
    rowPurpose: "Prepares, drafts, or executes according to Observe, Approval, or Direct mode.",
    allowedBlockTypes: ["neoblock", "tool", "capability", "gate"],
    preferredRoles: ["instruction", "primary", "metaTool"],
    routeRoles: ["executor"],
    siblingSemantics: "convergent",
    activationPolicy: "layout_only_until_route",
  },
  {
    rowId: "output",
    rowIndex: 8,
    rowLabel: "Output / Artifact / Report",
    rowPurpose: "Produces code, artifact, report, message, file, graph trace, or summary.",
    allowedBlockTypes: ["neoblock", "molt", "artifact"],
    preferredRoles: ["blueprint", "primary"],
    routeRoles: ["output"],
    siblingSemantics: "multi_select",
    activationPolicy: "activate_on_output_required",
  },
  {
    rowId: "audit_iteration",
    rowIndex: 9,
    rowLabel: "Audit / Feedback / Iteration",
    rowPurpose: "Logs actions, explains decisions, supports corrections and rerouting.",
    allowedBlockTypes: ["neoblock", "molt", "artifact"],
    preferredRoles: ["philosophy", "blueprint", "primary"],
    routeRoles: ["auditor"],
    siblingSemantics: "parallel",
    activationPolicy: "layout_only_until_route",
  },
];
