import { ComposeInput, ComposeResult, IRMatrixRow, MOLTRole, Sleeve, UMGBlock } from './types';
import { rolePriority } from './migrateLibrary';
const required: MOLTRole[] = ['directive','instruction','subject','primary','blueprint'];
const allRoles: MOLTRole[] = ['trigger','directive','instruction','subject','primary','philosophy','blueprint'];
const id = (p:string) => `${p}_${Math.random().toString(36).slice(2,8)}`;
const words = (s:string) => new Set(s.toLowerCase().replace(/[^a-z0-9\s-]/g,' ').split(/\s+/).filter(w=>w.length>2));
function inferTarget(req:string, t?:string){ if(t) return t; if(/chat|bot|faq|conversation/i.test(req)) return 'chatbot'; if(/template|intake|form/i.test(req)) return 'business_template'; if(/website|landing/i.test(req)) return 'website_prompt'; return 'umg_sleeve'; }
function inferTags(req:string, target:string, domain?:string){ const base=[target]; const dict=['chatbot','customer-support','intake','lead','summary','mobile-detailing','local-service-business','business-template','website','faq']; const low=req.toLowerCase(); return [...new Set([...base, ...(domain?[domain]:[]), ...dict.filter(t=>low.includes(t.replace(/-/g,' ')) || low.includes(t))])]; }
export function composeBlocks(input: ComposeInput, library: UMGBlock[]): ComposeResult { const depth=input.depth ?? 'balanced'; const target=inferTarget(input.freeform_request,input.target_type); const tags=inferTags(input.freeform_request,target,input.domain); const reqWords=words(input.freeform_request); const scored=library.map(b=>{ const tagMatches=b.tags.filter(t=>tags.includes(t) || reqWords.has(t)); const textWords=words(`${b.title} ${b.description??''} ${b.content} ${b.category??''} ${b.tags.join(' ')}`); let overlap=0; reqWords.forEach(w=>{ if(textWords.has(w)) overlap++; }); const roleMatch=required.includes(b.role)?1:0; const domainMatch=b.tags.some(t=>tags.includes(t))?1:0; const useCase=tagMatches.length>0?1:0; const score=roleMatch*25 + tagMatches.length*10 + domainMatch*20 + useCase*20 + Math.max(0,20-(b.priorityOrder??rolePriority[b.role])) + overlap*3 - (b.conflicts?.length??0)*5; return {...b, score, tagsMatched:tagMatches, reason:`score ${score}: role=${b.role}, matched tags=${tagMatches.join(', ') || 'none'}`}; }).sort((a,b)=> b.score-a.score || (a.priorityOrder??0)-(b.priorityOrder??0));
 const selected: typeof scored=[]; const max = depth==='lean'?5:depth==='balanced'?9:14; for(const role of required){ const pick=scored.find(b=>b.role===role && !selected.some(s=>s.id===b.id)); if(pick) selected.push(pick); }
 if(depth!=='lean') for(const role of ['trigger','philosophy'] as MOLTRole[]){ const pick=scored.find(b=>b.role===role && !selected.some(s=>s.id===b.id)); if(pick) selected.push(pick); }
 for(const b of scored){ if(selected.length>=max) break; if(!selected.some(s=>s.id===b.id) && b.score>15) selected.push(b); }
 selected.sort((a,b)=>(a.priorityOrder??0)-(b.priorityOrder??0)); const missing=required.filter(r=>!selected.some(b=>b.role===r)); const sleeve:Sleeve={ id:id('slv'), title: target==='chatbot'?'Customer Intake Chatbot': target.replace(/_/g,' ').replace(/\b\w/g,m=>m.toUpperCase()), type:'sleeve', version:'0.1', description:`Draft sleeve for: ${input.freeform_request}`, tags, stacks:[{ id:id('stk'), title: target==='chatbot'?'Chatbot Conversation Stack':'Composed UMG Stack', type:'neostack', tags, role:target as any, defaultState:'on', compileStrategy:'role_then_priority', neoblocks:[{ id:id('nb'), title: target==='chatbot'?'Intake Capture':'Composed NeoBlock', type:'neoblock', tags, blocks:selected, defaultState:'on', priorityOrder:10, activation:{mode:'always'}}]}], runtimeConfig:{active:true, depth, hermesEnabled:!!input.hermes_assist, runtimeAdaptation:false, showRuntimeTrace:true}, metadata:{createdAt:new Date().toISOString(), author:'UMG Studio v0.1'}}; const seed:IRMatrixRow[]=selected.map((b,i)=>({rowId:`ir_${i+1}`, nodeId:b.id, nodeType:'molt_block', role:b.role, title:b.title, selected:true, active:b.defaultState==='on', off:b.defaultState==='off', triggered:false, required:required.includes(b.role), tagsMatched:b.tagsMatched, relevanceScore:b.score, priority:b.priorityOrder, contribution:b.content})); return {composition_id:id('cmp'), request:input.freeform_request, classification:{target_type:target, domain:input.domain??(tags.includes('mobile-detailing')?'mobile_detailing':'general'), depth, tags}, selected_nodes:selected, rejected_nodes:scored.filter(b=>!selected.some(s=>s.id===b.id)).slice(0,20).map(b=>({id:b.id,title:b.title,reason:`lower score ${b.score}`})), warnings:missing.map(r=>`Missing recommended role: ${r}`), draft_sleeve:sleeve, ir_matrix_seed:seed}; }
