export type MOLTRole = 'trigger'|'directive'|'instruction'|'subject'|'primary'|'philosophy'|'blueprint';
export type MOLTDisplayType = MOLTRole|'meta';
export type NodeKind = 'sleeve'|'neostack'|'neoblock'|'molt_block'|'gate'|'output';
export type LibraryAssetStatus = 'runnable'|'reference-only'|'unsupported'|'warning-bearing'|'meta';
export type UMGBlock = { id:string; title:string; type:'molt_block'; role:MOLTRole; displayType?:MOLTDisplayType; content:string; description?:string; category?:string; tags:string[]; priorityOrder?:number; hierarchy?:BlockHierarchy; defaultState:'on'|'off'; visibility:'visible'|'collapsed'|'audit_only'; activation?:{mode:'always'|'tag_match'|'manual'|'gate'; tags?:string[]; gateId?:string}; dependencies?:string[]; conflicts?:string[]; compatibleSleeves?:string[]; compatibleStacks?:string[]; action?:string; expectedOutput?:string; sourcePath?:string; sourceLayer?:'AI'|'HUMAN'|'sleeves'|string; status?:LibraryAssetStatus; source?:{origin:'library'|'workspace'|'imported'|'generated'; sourceId?:string; version?:string}; presentationStatus?:LibraryAssetStatus; createdAt?:string; updatedAt?:string; legacy?:{sourceRepo?:string; original:unknown; sourcePath?:string; migrationWarnings?:string[]; originalFilename?:string; originalMarkdown?:string; detectedHeading?:string; parseWarnings?:string[]; parentSourcePath?:string; libraryEntryId?:string}};
export type BlockHierarchy = { orderIndex?: number; orderSource: 'priorityOrder'|'source'|'default'; priorityMeaning: 'hierarchy_order' };
// Phase3C Option B: rootController is first-class scope authority, not an ordinary child.
export type UMGScopeKind = 'sleeve'|'neostack'|'neoblock_subgraph';
export type UMGControllerKind = 'sleeve_root'|'neostack_root'|'neoblock_subgraph_root';
// Phase3C Option B: controller payloads reuse normal MOLT blocks and may carry directive-bundle metadata.
export type UMGDirectiveBundle = { ownerBlockId:string; directives:UMGDirectiveBundleItem[]; defaultDirectiveId?:string; activeDirectiveId?:string; activationPolicy:'priority_order'|'gate_selected'|'manual_selected' };
export type UMGDirectiveBundleItem = { moltId:string; priority:number; label:string; activationTriggerKey?:string; compatibleWith?:string[]; conflictsWith?:string[]; defaultState:'active'|'dormant' };
export type UMGControllerBlock = { id:string; title:string; controllerKind:UMGControllerKind; ownerScopeKind:UMGScopeKind; ownerScopeId:string; molts:UMGBlock[]; directiveBundle?:UMGDirectiveBundle; metadata?:{ domainTags?:string[]; scopePurpose?:string; version?:string; createdBy?:'compose'|'user'|'migration'|'fallback'|'virtual'; [key:string]:unknown } };
// Phase3C Option B: segment layout is metadata for the row/slot authority graph of a scope.
// Gates here are control records, not MOLT prompt content.
export type UMGSegmentLayout = { id:string; ownerScopeKind:UMGScopeKind; ownerScopeId:string; version:'segment-slot-root-controller-v1'; rows:UMGSegmentRow[]; slots:UMGSegmentSlot[]; relations:UMGSegmentRelation[]; gates:UMGSegmentGate[]; routePreview?:UMGRoutePreviewState; layoutWarnings?:string[] };
export type UMGSegmentRowRole = 'root_controller'|'strategy'|'domain'|'specialization'|'detail'|'custom';
export type UMGSegmentRow = { id:string; index:number; label:string; role:UMGSegmentRowRole; collapsed?:boolean };
export type UMGSlotOccupantKind = 'root_controller'|'scope_child'|'empty'|'compressed_branch';
export type UMGScopeChildKind = 'neostack'|'neoblock'|'future_child';
export type UMGSegmentSlot = { id:string; rowId:string; rowIndex:number; columnIndex:number; occupantKind:UMGSlotOccupantKind; occupantId?:string; occupantScopeChildKind?:UMGScopeChildKind; parentSlotId?:string; collapsed?:boolean; visualWidth?:'compact'|'normal'|'wide' };
export type UMGSegmentRelationKind = 'authority_child'|'peer_complement'|'gated_route'|'suppression'|'escalation_signal'|'compressed_branch';
export type UMGSegmentRelation = { id:string; kind:UMGSegmentRelationKind; sourceSlotId:string; targetSlotId:string; gateId?:string; label?:string; priority?:number; enabled?:boolean };
export type UMGGateAction = 'activate_target'|'suppress_target'|'select_route'|'activate_directive'|'emit_escalation_signal';
export type UMGGateMode = 'manual'|'static_condition'|'future_runtime';
export type UMGSegmentGate = { id:string; label:string; sourceSlotId?:string; targetSlotId?:string; triggerKey?:string; conditionText?:string; action:UMGGateAction; mode:UMGGateMode; targetDirectiveId?:string; targetControllerId?:string; targetChildId?:string; defaultState?:'open'|'closed'|'unknown' };
export type UMGEscalationSignal = { id:string; fromSlotId:string; toSlotId?:string; triggerKey?:string; label?:string; reason?:string };
export type UMGRoutePreviewState = { mode:'static_preview'|'future_agentic'; activeControllerIds:string[]; activeDirectiveIds:string[]; activeSlotIds:string[]; dormantSlotIds:string[]; suppressedSlotIds:string[]; openGateIds:string[]; closedGateIds:string[]; escalationSignals:UMGEscalationSignal[]; warnings?:string[] };
export type SearchCard = { type:'SearchCard'; id:string; title:string; role:MOLTRole; category?:string; tags:string[]; sourcePath?:string; status?:LibraryAssetStatus; hierarchy:BlockHierarchy; summary?:string };
export type RuntimeBlock = { type:'RuntimeBlock'; id:string; title:string; role:MOLTRole; content:string; nl:string; action?:string; expectedOutput?:string; tags:string[]; hierarchy:BlockHierarchy; compiler:{ source:'compiler_aligned_json'; moltType:MOLTRole }; runtimeState:{ defaultState:'on'|'off'; selected:boolean; active:boolean; off:boolean; triggered:boolean } };
export type FullSourceRecord = { type:'FullSourceRecord'; sourcePath?:string; sourceLayer?:string; legacyOriginal?:unknown; normalized:UMGBlock };
export type GateKind = 'trigger_gate'|'routing_gate'|'governance_gate'|'action_gate';
export type GateTargetType = 'molt_block'|'neoblock'|'neostack'|'sleeve_route'|'tool_proposal';
export type GatePathState = 'active'|'dormant'|'suppressed'|'blocked';
export type GateVisualPathState = GatePathState|'candidate'|'requires_approval'|'evaluating';
export type RuntimeGateState = 'inactive'|'evaluating'|'passed'|'dormant'|'suppressed'|'blocked'|'requires_approval'|'rejected';
export type GateScopeTarget = { targetId:string; targetType:GateTargetType; defaultPathState:GatePathState };
export type GateRouteControl = { activates:GateScopeTarget[]; dormants:GateScopeTarget[]; suppresses:GateScopeTarget[]; blocks:GateScopeTarget[] };
export type GateRuntimeState = { state:RuntimeGateState; passed:boolean; reason:string };
export type GatePriorityOrder = { orderIndex?:number; priorityMeaning:'hierarchy_order_only' };
export type GateCard = { type:'GateCard'; id:string; title:string; gateKind:GateKind; category?:string; tags:string[]; sourcePath?:string; sourceLayer?:string; status?:LibraryAssetStatus; summary?:string; governs:GateScopeTarget[] };
export type TriggerGateSourceCard = { type:'TriggerGateSourceCard'; id:string; title:string; gateKind:'trigger_gate'; sourceType:'HUMAN_GATE_SOURCE'; sourceLayer:'HUMAN'; sourcePath:string; status:string; category:string; subcategory:string; tags:string[]; summary:string; activation:{ mode:'source_condition'|'manual_candidate'; conditionSummary:string; rawActivation?:string; hasExplicitActivation:boolean }; card:{ displayType:'trigger_gate_source'; badge:'Gt'; familyLabel:'TriggerGate Source'; runnableAsPromptContent:false; addActionLabel:'Attach Gate' }; legacy:{ originalMarkdown:string; parsedHeadings:Record<string,string>; parseWarnings:string[] } };
export type RuntimeGatePlacement = { kind:'node_boundary'|'edge'; targetId:string };
export type RuntimeGate = { type:'RuntimeGate'; id:string; title:string; gateKind:GateKind; condition:string; routeControl:GateRouteControl; runtimeState:GateRuntimeState; priorityOrder:GatePriorityOrder; traceRefs:string[]; sourcePath?:string; sourceCardId?:string; placement?:RuntimeGatePlacement };
export type FullGateSourceRecord = { type:'FullGateSourceRecord'; sourcePath:string; sourceLayer:'HUMAN'; sourceFamily:'HUMAN/GATES'; legacyOriginal:{ markdown:string; parsedFields:Record<string,string>; parsedHeadings:Record<string,string> }; normalized:TriggerGateSourceCard; parserVersion:'trigger-gate-source-card.v0.1'; warnings:string[] };
export type GateIRRow = { rowId:string; nodeId:string; nodeType:'gate'; gateKind:GateKind; title:string; selected:false; active:false; off:false; triggered:false; required:false; tagsMatched:string[]; state:RuntimeGateState|GatePathState; gatePassed:boolean; selectedRouteIds:string[]; activeTargetIds:string[]; dormantTargetIds:string[]; suppressedTargetIds:string[]; blockedTargetIds:string[]; governedNodeIds:string[]; requiredApproval:boolean; routingDecision?:string; reason:string; traceEventIds:string[] };
export type GateEvaluationMode = 'manual' | 'text_tag' | 'policy' | 'manual_override' | 'disabled';
export type GateEvaluationOutcome = 'passed' | 'blocked' | 'dormant' | 'suppressed' | 'requires_approval' | 'not_applicable' | 'error';
export type GateEvaluationTargetDecision = {
  targetId: string;
  targetType: GateTargetType;
  requestedPathState: GatePathState;
  winnerPolicy: 'pass' | 'conflict' | 'default' | 'override';
  evidence: Array<{ source: string; value: string; traceEventId?: string }>;
  overridesBy?: string[];
};
export type GateEvaluationRouteSelections = {
  selectedRouteIds: string[];
  activeTargets: string[];
  dormantTargets: string[];
  suppressedTargets: string[];
  blockedTargets: string[];
  requiresApprovalTargets: string[];
};
export type GateEvaluationResult = {
  gateId: string;
  gateKind: GateKind;
  evaluatedAt: string;
  evaluationMode: GateEvaluationMode;
  outcome: GateEvaluationOutcome;
  decision: RuntimeGateState;
  passed: boolean;
  confidence?: number;
  reason: string;
  routeSelections: GateEvaluationRouteSelections;
  targetDecisions: GateEvaluationTargetDecision[];
  selectedRouteId?: string;
  requiresApproval: boolean;
  safety: {
    promptContentMutation: boolean;
    routeSwitching: boolean;
    liveExecution: boolean;
    toolExecution: boolean;
  };
  traceEventIds: string[];
};
export type GateEvaluationInput = {
  gate: RuntimeGate;
  evaluationMode?: GateEvaluationMode;
  triggerMatch?: boolean;
  routePriority?: number;
  evaluationReason?: string;
  selectedRouteId?: string;
  evaluatedAt?: string;
  confidence?: number;
  traceEventIds?: string[];
};
export type GateDecision = { gateId:string; gateKind:GateKind; decision:RuntimeGateState|GatePathState; reason:string; targetIds:string[] };
export type GateRouteState = { active_paths:string[]; dormant_paths:string[]; suppressed_paths:string[]; blocked_paths:string[] };
export type RuntimeGateContext = { gates:Array<Pick<RuntimeGate,'id'|'sourceCardId'|'title'|'gateKind'|'sourcePath'|'runtimeState'|'placement'>>; gate_decisions:GateDecision[]; route_state:GateRouteState };
export type RuntimeSpecGateContext = { gates:RuntimeGate[]; route_state:GateRouteState; gate_decisions:GateDecision[]; active_blocks:string[]; inactive_blocks?:{ dormant:string[]; suppressed:string[]; blocked:string[] } };
export type HermesGatePacketContext = { gate_context?:{ gates:RuntimeGate[]; gate_decisions:GateDecision[]; route_state:GateRouteState }; action_gates?:ActionGate[]; tool_proposals?:ToolProposal[]; tool_results?:ToolResult[] };
export type ToolProposal = { id:string; blockId:string; title:string; proposedAction:string; status:'proposed'|'gated'|'rejected' };
export type ActionGate = { id:string; proposalId:string; requiredApproval:boolean; state:'closed'|'open'|'approved'|'rejected'|'requires_approval' };
export type ToolResult = { id:string; proposalId:string; ok:boolean; output?:unknown; error?:string };
export type NeoBlock = { id:string; title:string; type:'neoblock'; description?:string; category?:string; tags:string[]; blocks:UMGBlock[]; defaultState:'on'|'off'; priorityOrder?:number; activation?:{mode:'always'|'tag_match'|'manual'|'gate'; tags?:string[]; gateId?:string}};
export type NeoStack = { id:string; title:string; type:'neostack'; description?:string; tags:string[]; neoblocks:NeoBlock[]; directBlocks?:UMGBlock[]; role?:'chatbot'|'business_template'|'website_prompt'|'runtime'|'general'; defaultState:'on'|'off'; compileStrategy?:'ordered'|'priority'|'role_then_priority'; rootController?:UMGControllerBlock; segmentLayout?:UMGSegmentLayout };
export type Sleeve = { id:string; title:string; type:'sleeve'; version:string; description?:string; tags:string[]; stacks:NeoStack[]; rootController?:UMGControllerBlock; segmentLayout?:UMGSegmentLayout; runtimeConfig:{active:boolean; depth:'lean'|'balanced'|'full'; hermesEnabled:boolean; runtimeAdaptation:boolean; showRuntimeTrace:boolean}; metadata?:{author?:string; createdAt?:string; updatedAt?:string}};
export type GraphFocusMode = 'sleeve'|'neostack'|'neoblock'|'molt_block';
export type GraphFocus = { mode:GraphFocusMode; sourceId?:string };
export type LayoutRelation = 'governs'|'parallel'|'supports'|'fallback'|'sequence'|'contains';
export type GraphLayoutItem = { x?:number; y?:number; row?:number; column?:number; width?:number; height?:number; span?:number; priorityRank?:number; relation?:LayoutRelation; manual?:boolean; manualOverride?:boolean; locked?:boolean; snapTargetId?:string; snapGroupId?:string };
export type GraphNode = { id:string; sourceId:string; nodeType:NodeKind; label:string; position:{x:number;y:number}; layout?:GraphLayoutItem; state:{selected:boolean; active:boolean; off:boolean; triggered:boolean; invalid:boolean; warning?:string}; visual?:{focused:boolean; dimmed:boolean; hidden?:boolean}; pathState?:GateVisualPathState; governingGateIds?:string[]; gateKind?:GateKind; gateLabel?:string; glyphId?:string; debugExpandable?:boolean; moltRole?:MOLTDisplayType | 'unknown'; };
export type GraphEdge = { id:string; source:string; target:string; type:'contains'|'depends_on'|'activates'|'conflicts_with'|'compiles_to'|'generates'|'fallback_to'; label?:string; pathState?:GateVisualPathState; governingGateId?:string; gateKind?:GateKind; gateLabel?:string; routeId?:string; governanceOverride?:boolean };
export type Diagnostic = { id:string; type:string; severity:'info'|'warning'|'error'; message:string; nodeId?:string };
export type IRMatrixRow = { rowId:string; nodeId:string; nodeType:string; role?:string; title:string; selected:boolean; active:boolean; off:boolean; triggered:boolean; gatePassed?:boolean; pathState?:GatePathState; governingGateIds?:string[]; required:boolean; tagsMatched:string[]; relevanceScore?:number; priority?:number; contribution?:string; warning?:string };
export type RuntimeSession = { id:string; request:string; activeSleeveId:string; compiledAt?:string; generatedAt?:string; runtimeSpec?:unknown; trace?:unknown; irMatrix?:IRMatrixRow[]; compiledPrompt?:string; hermesOutput?:string; diagnostics:Diagnostic[] };
export type UMGWorkspace = { id:string; title:string; activeSleeveId?:string; sleeves:Sleeve[]; libraryRefs:string[]; graph:{nodes:GraphNode[]; edges:GraphEdge[]; viewport?:{zoom:number;x:number;y:number;focusNodeId?:string}}; runtimeGates?:RuntimeGate[]; runtime?:RuntimeSession };
export type ComposeInput = { freeform_request:string; target_type?:'chatbot'|'business_template'|'website_prompt'|'umg_sleeve'; domain?:string; tone?:string; depth?:'lean'|'balanced'|'full'; hermes_assist?:boolean };
export type ComposeResult = { composition_id:string; request:string; classification:{target_type:string; domain:string; depth:'lean'|'balanced'|'full'; tags:string[]}; selected_nodes:Array<UMGBlock & {score:number; reason:string; tagsMatched:string[]}>; rejected_nodes:Array<{id:string; title:string; reason:string}>; warnings:string[]; draft_sleeve:Sleeve; ir_matrix_seed:IRMatrixRow[] };
export type CompileResult = { runtimeSpec:unknown; trace:Array<Record<string, unknown>>; diagnostics:Diagnostic[]; promptPreview:string; irMatrix:IRMatrixRow[] };
export type HermesConfig = { endpoint:string; apiKey?:string; model:string; temperature:number; maxTokens:number };
