import { useMemo, useState } from 'react';
import './style.css';
import rawBlocks from '../data/library/blocks.json';
import { normalizeImportedBlocks } from './lib/umg/migrateLibrary';
import { composeBlocks } from './lib/umg/composeBlocks';
import { applyCompileResultToGraph, buildGraphFromSleeve } from './lib/umg/graphBuilder';
import { compileWorkspaceToRuntime } from './lib/umg/compilerBridge';
import { downloadJson, exportHermesPacket } from './lib/umg/exporters';
import { generateWithHermes, redactKey, testHermesConnection } from './lib/hermes/hermesClient';
import { CompileResult, GraphNode, HermesConfig, UMGBlock, UMGWorkspace } from './lib/umg/types';
const demo='Build me a customer-intake chatbot for a mobile detailing business. It should answer basic questions, collect customer name, vehicle type, location, service need, and budget, then produce a clean lead summary.';
export default function App(){
 const [mode,setMode]=useState<'simple'|'builder'|'creator'>('simple'); const [request,setRequest]=useState(demo); const [target,setTarget]=useState('chatbot'); const [depth,setDepth]=useState<'lean'|'balanced'|'full'>('balanced'); const [library,setLibrary]=useState<UMGBlock[]>(()=>normalizeImportedBlocks(rawBlocks as unknown[])); const [workspace,setWorkspace]=useState<UMGWorkspace|undefined>(); const [selected,setSelected]=useState<GraphNode|undefined>(); const [compiled,setCompiled]=useState<CompileResult|undefined>(); const [tab,setTab]=useState('Prompt'); const [filter,setFilter]=useState('all'); const [search,setSearch]=useState(''); const [config,setConfig]=useState<HermesConfig>({endpoint:import.meta.env.VITE_HERMES_ENDPOINT||'', apiKey:import.meta.env.VITE_HERMES_API_KEY||'', model:import.meta.env.VITE_HERMES_MODEL||'hermes-default', temperature:.3, maxTokens:1200}); const [output,setOutput]=useState(''); const [status,setStatus]=useState('ready');
 const composed=()=>{ const c=composeBlocks({freeform_request:request,target_type:target as any,depth},library); const graph=buildGraphFromSleeve(c.draft_sleeve); setWorkspace({id:'ws_local',title:'Local UMG Workspace',activeSleeveId:c.draft_sleeve.id,sleeves:[c.draft_sleeve],libraryRefs:library.map(b=>b.id),graph}); setCompiled(undefined); setStatus(`composed ${c.selected_nodes.length} nodes; ${c.warnings.length} warnings`); };
 const compile=()=>{ if(!workspace) return setStatus('no workspace'); const c=compileWorkspaceToRuntime(workspace,{tags:['chatbot','intake','mobile-detailing']}); const graph=applyCompileResultToGraph(workspace.graph,c); setWorkspace({...workspace,graph,runtime:{id:`run_${Date.now()}`,request,activeSleeveId:workspace.activeSleeveId||workspace.sleeves[0].id,compiledAt:new Date().toISOString(),runtimeSpec:c.runtimeSpec,trace:c.trace,irMatrix:c.irMatrix,compiledPrompt:c.promptPreview,diagnostics:c.diagnostics}}); setCompiled(c); setTab('Prompt'); setStatus(`compiled with ${c.diagnostics.length} diagnostics`); };
 const toggleNode=(n:GraphNode)=>{ if(!workspace) return; const ws=structuredClone(workspace); for(const s of ws.sleeves[0].stacks) for(const nb of s.neoblocks) for(const b of nb.blocks) if(b.id===n.sourceId) b.defaultState=b.defaultState==='off'?'on':'off'; ws.graph=buildGraphFromSleeve(ws.sleeves[0]); setWorkspace(ws); setSelected(undefined); setCompiled(undefined); };
 const addBlock=(b:UMGBlock)=>{ if(!workspace){setStatus('compose a workspace first');return;} const ws=structuredClone(workspace); ws.sleeves[0].stacks[0].neoblocks[0].blocks.push({...b,id:`${b.id}_copy_${Date.now()}`,source:{origin:'workspace',sourceId:b.id,version:'0.1'}}); ws.graph=buildGraphFromSleeve(ws.sleeves[0]); setWorkspace(ws); setStatus(`added workspace copy of ${b.title}`); };
 const visible=library.filter(b=>(filter==='all'||b.role===filter)&&(`${b.title} ${b.tags.join(' ')} ${b.content}`.toLowerCase().includes(search.toLowerCase())));
 const nodeJson=selected?findSource(workspace,selected.sourceId):undefined;
 return <div className="app"><header><div><b>UMG Studio v0.1</b><span>local graph cognition studio</span></div><nav>{['simple','builder','creator'].map(m=><button className={mode===m?'hot':''} onClick={()=>setMode(m as any)}>{m}</button>)}</nav><button onClick={()=>downloadJson('umg-workspace.json',workspace)}>Export Workspace</button></header>
 <main><section className="compose card"><h2>Compose</h2><textarea value={request} onChange={e=>setRequest(e.target.value)} /><div className="row"><select value={target} onChange={e=>setTarget(e.target.value)}><option value="chatbot">Chatbot</option><option value="business_template">Business Template</option><option value="website_prompt">Website Prompt</option><option value="umg_sleeve">UMG Sleeve</option></select><select value={depth} onChange={e=>setDepth(e.target.value as any)}><option>lean</option><option>balanced</option><option>full</option></select><button className="primary" onClick={composed}>Compose Blocks</button><button onClick={compile}>Compile</button><button onClick={async()=>{ if(!compiled) return setStatus('compile first'); const r=await generateWithHermes(request,compiled,config); setOutput(r.output); setTab('Output'); setStatus(r.ok?'Hermes generation complete':'Hermes generation blocked');}}>Generate</button></div><p>{status}</p></section>
 <section className="library card"><h2>Library</h2><input placeholder="search" value={search} onChange={e=>setSearch(e.target.value)} /><select value={filter} onChange={e=>setFilter(e.target.value)}><option>all</option>{['trigger','directive','instruction','subject','primary','philosophy','blueprint'].map(r=><option>{r}</option>)}</select><div className="cards">{visible.map(b=><div className="block" key={b.id}><b>{b.title}</b><small>{b.role} • {b.category}</small><p>{b.content}</p><em>{b.tags.join(', ')}</em><button onClick={()=>addBlock(b)}>Add workspace copy</button></div>)}</div></section>
 <section className="graph card"><div className="bar"><h2>Graph Studio</h2><button onClick={()=>workspace&&downloadJson('sleeve.json',workspace.sleeves[0])}>Export Sleeve</button><button onClick={()=>compiled&&downloadJson('ir-matrix.json',compiled.irMatrix)}>Export IR</button><button onClick={()=>compiled&&downloadJson('hermes-packet.json',exportHermesPacket(request,compiled,config))}>Export Hermes Packet</button></div>{workspace?<Graph nodes={workspace.graph.nodes} edges={workspace.graph.edges} selected={selected?.id} onPick={setSelected}/>:<div className="empty">Describe what you want to build, then click Compose Blocks.</div>}</section>
 <aside className="inspect card"><h2>Inspector</h2>{selected?<><b>{selected.label}</b><p>{selected.nodeType} / {selected.state.off?'off':'active'}</p>{selected.nodeType==='molt_block'&&<button onClick={()=>toggleNode(selected)}>Toggle on/off</button>}<pre>{JSON.stringify(nodeJson??selected,null,2)}</pre></>:<p>Select a graph node.</p>}<h2>Config</h2><input placeholder="Hermes endpoint" value={config.endpoint} onChange={e=>setConfig({...config,endpoint:e.target.value})}/><input placeholder="API key" value={config.apiKey||''} onChange={e=>setConfig({...config,apiKey:e.target.value})}/><small>redacted: {redactKey(config.apiKey)}</small><input value={config.model} onChange={e=>setConfig({...config,model:e.target.value})}/><button onClick={async()=>setStatus((await testHermesConnection(config)).message)}>Test connection</button></aside>
 <section className="drawer card"><h2>Compiler / Runtime</h2><div className="tabs">{['Input JSON','RuntimeSpec','Trace','Prompt','Diagnostics','IR Matrix','Output'].map(t=><button className={tab===t?'hot':''} onClick={()=>setTab(t)}>{t}</button>)}</div><pre>{renderTab(tab,workspace,compiled,output)}</pre></section></main></div> }
function Graph({nodes,edges,selected,onPick}:{nodes:GraphNode[];edges:any[];selected?:string;onPick:(n:GraphNode)=>void}){ return <div className="canvas"><svg>{edges.map(e=>{const a=nodes.find(n=>n.id===e.source),b=nodes.find(n=>n.id===e.target); if(!a||!b)return null; return <line key={e.id} x1={a.position.x+90} y1={a.position.y+24} x2={b.position.x} y2={b.position.y+24}/>})}</svg>{nodes.map(n=><button key={n.id} onClick={()=>onPick(n)} className={`node ${n.nodeType} ${n.state.off?'off':'active'} ${n.state.triggered?'triggered':''} ${n.state.warning?'warning':''} ${n.state.invalid?'invalid':''} ${selected===n.id?'picked':''}`} style={{left:n.position.x,top:n.position.y}}><b>{n.label}</b><small>{n.nodeType}{n.state.triggered?' ⚡':''}{n.state.warning?' ⚠':''}</small></button>)}</div> }
function findSource(ws:UMGWorkspace|undefined,id:string){ if(!ws) return undefined; const s=ws.sleeves[0]; if(s.id===id) return s; for(const st of s.stacks){ if(st.id===id)return st; for(const nb of st.neoblocks){ if(nb.id===id)return nb; for(const b of nb.blocks) if(b.id===id)return b; }} }
function renderTab(tab:string,ws?:UMGWorkspace,c?:CompileResult,out?:string){ if(tab==='Input JSON') return JSON.stringify(ws?.sleeves[0]??{},null,2); if(tab==='RuntimeSpec') return JSON.stringify(c?.runtimeSpec??{},null,2); if(tab==='Trace') return JSON.stringify(c?.trace??[],null,2); if(tab==='Prompt') return c?.promptPreview??''; if(tab==='Diagnostics') return JSON.stringify(c?.diagnostics??[],null,2); if(tab==='IR Matrix') return JSON.stringify(c?.irMatrix??[],null,2); return out||'No output yet.'; }
